version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
#    environment:
#      - DATABASE_URL=postgresql://martin:password@db:5432/mydb
    volumes:
      - .:/conversation_agent
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=martin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: